name: SWG - Doc matching
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
jobs:
  download-and-match:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Perform matching
        env:
          SWGDOCMATCH_GS_URL: ${{ secrets.SWGDOCMATCH_GS_URL }}
      - name: Commit new versions of files
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          message: "SWG - doc matching"
          default_author: github_actions

  call-entail-validate-changes-workflow:
    needs: download-and-match
    uses: ./.github/workflows/entail_and_validate_changes.yml
    with:
      files-modified: incubation/working-groups/docs.ttl
      repo-ref: ${{ github.ref_name }}